### PR TITLE
Remove invalid skos:member

### PR DESCRIPTION
**Pull request by jennet**
`skos:member` is only valid between a `skos:Collection` and a `skos:Concept`. This PR removes the CSVW configuration that generate `?concept-scheme skos:member ?concept` triples

Valid ways of linking concepts to concept schemes are `?concept skos:inScheme ?concept-scheme` and there isn't an inverse predicate for this

Collections are disjoint from ConceptSchemes and so cannot have the same subject URI.

### CODE REVIEW

**Comment by jennet** [comment]
@lkitching Should I also remove all `skos:member` triples from the example TTL files in this PR?

**Comment by jennet** [comment]
https://github.com/Swirrl/table2qb/issues/118

**Comment by lkitching** [comment]
@jennet - If you could that would be great. The rest looks good to me!

**Comment by jennet** [comment]
@lkitching done!

**Comment by RickMoynihan** [comment]
Looks like there was already another PR for this https://github.com/Swirrl/table2qb/pull/90 just mentioning it to associate the issues/PRs together.  Will close these too.

**Pull request merged**
